title: tuhinm
description: Tuhin M's portfolio
url: https://tuhinmukherjee.github.io

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sourcemap: never

lowercase: false
newtab: false